# -*- coding: utf-8 -*-
#
# This file is part of Invenio Demosite.
# Copyright (C) 2015 CERN.
#
# Invenio Demosite is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio Demosite is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip

notifications:
  email: false

services:
  - mysql
  - redis
  - elasticsearch

language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - apache2
      - git
      - liblzma-dev
      - nodejs
      - poppler-utils

env:
  - REQUIREMENTS=cdslabs
  - REQUIREMENTS=cdslabs_qa

before_install:
  - "travis_retry pip install mock"

install:
  - "travis_retry pip install -r requirements.$REQUIREMENTS.txt --exists-action i"
  - "travis_retry pip install nose"
  - "travis_retry pip install unittest2"
  - "npm update"
  - "npm install --silent -g bower less clean-css uglify-js requirejs"
  - "inveniomanage config create secret-key"
  - "inveniomanage config set CFG_SITE_URL http://localhost"
  - "inveniomanage config set CFG_SITE_SECURE_URL https://localhost"
  - "inveniomanage config set CFG_EMAIL_BACKEND flask.ext.email.backends.console.Mail"
  - "inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami`"
  - "inveniomanage config set LESS_BIN /bin/true"  # silent the warnings
  - "inveniomanage config set CLEANCSS_BIN /bin/true"
  - "inveniomanage config set REQUIREJS_BIN /bin/true"
  - "inveniomanage config set UGLIFYJS_BIN /bin/true"
  - "inveniomanage config set ASSETS_DEBUG True"  # ignore assets issues
  - "inveniomanage config set LESS_RUN_IN_DEBUG False"
  - "inveniomanage config set REQUIREJS_RUN_IN_DEBUG False"

before_script:
  - "inveniomanage apache create-config"
  - "inveniomanage database init --yes-i-know || echo ':('"
  - "inveniomanage database create --quite || echo ':('"
  # - "inveniomanage records create -t marcxml < cds/demosite/data/cds-demobibdata.xml"

script:
  - "python setup.py test"
